import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Wine Storage Temperature Monitor",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="grid min-h-[100dvh] grid-rows-[auto_1fr_auto]">
          <header className='bg-green-600 text-white p-5 text-left text-2xl font-bold'>
            Wine Storage Temperature
          </header>
          {children}
          <footer>
            <div className='bg-green-600 text-white p-3 text-center'>
              &copy; 2025 Wine Storage Inc.
            </div>
          </footer>
        </div>
      </body>
    </html>
  );
}
